# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbc5784448860b5315d215a18578000e3a412cd1f9391c0c81490b109cd3bbbd69220533a7876f40560ed0273a914551df040f9832d838e7a2b165ae8d502379

test:
  secret_key_base: 9977caff69d6134ad79e45febe8d49af5a1a6982b1f802f0fbc141c27114ba9083ce070896ac4200011fcaf461eec6e62ac539d9654625a07c463d3edc21acd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
